server {
    listen 80;
    server_name fiberco.com.au www.fiberco.com.au;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name fiberco.com.au www.fiberco.com.au;

    ssl_certificate /etc/letsencrypt/live/fiberco.com.au/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fiberco.com.au/privkey.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    resolver 127.0.0.11 valid=10s;
    set $upstream_website fiberco-website-app:3000;

    location / {
        proxy_pass http://$upstream_website;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
