worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile    on;
    tcp_nopush  on;
    keepalive_timeout 65;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # Include all project route configs
    include /etc/nginx/conf.d/*.conf;

    # Default — return 444 for unmatched hosts
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }
}
